### ISSUE TITLE
mcMMO minecraft plugin and Occultism conflict.

### ISSUE THREAD

**Issue by Pantymane** [klikli-dev/occultism#1019]
**Describe your problem**
Hi! I'm running a hybrid 1.20.1 server and i have a conflict between Occultism and a plugin named(mcMMO)mcMMO 
,when i run it with the mod, mcMMO stops working, but the server loads up just fine, the error happenes 
during mcMMO's recipe conversion(Shapeless recipes cannot have more than 9 ingredients). 
Here is the part of the log that mentions the problem:

[19dec.2023 21:59:00.709] [Server thread/ERROR] [mcMMO/]: There was an error while enabling mcMMO!
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Error converting recipe occultism:ritual/possess_elder_guardian
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.craftbukkit.v1_20_R1.inventory.RecipeIterator.next(RecipeIteratorMixin.java:554)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.craftbukkit.v1_20_R1.inventory.RecipeIterator.next(RecipeIteratorMixin.java:1)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:329)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:146)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:28)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:593)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:208)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.handler$cno000$arclight$enablePlugins(MinecraftServerMixin.java:2137)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:162)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: Caused by: java.lang.IllegalArgumentException: Shapeless recipes cannot have more than 9 ingredients
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.inventory.ShapelessRecipe.addIngredient(ShapelessRecipe.java:130)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.crafting.ShapelessRecipe.bridge$toBukkitRecipe(ShapelessRecipeMixin.java:538)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.craftbukkit.v1_20_R1.inventory.RecipeIterator.next(RecipeIteratorMixin.java:552)
[19dec.2023 21:59:00.709] [Server thread/ERROR] [STDERR/]: 	... 19 more
[19dec.2023 21:59:00.709] [Server thread/INFO] [mcMMO/]: Disabling mcMMO v2.1.224
[19dec.2023 21:59:00.709] [Server thread/INFO] [mcMMO/]: Server shutdown has been executed, saving and cleaning up data...
[19dec.2023 21:59:00.712] [Server thread/INFO] [mcMMO/]: [D] Completing 0 unfinished Alchemy brews.
[19dec.2023 21:59:00.717] [Server thread/INFO] [mcMMO/]: [D] [Party Data] Saving...

**System (please complete the following information):**
- Minecraft Version 1.20.1
- Modpack Link and Version, or list of mods Forge 47.1.1
- Specific mods that you experience compatiblity issues with: A plugin called mcMMO

**Comment by klikli-dev** [comment]
Hmm it seems mcMMO checks for the recipe java class "ShapelessRecipe", instead of the RecipeType that datapacks use.
That is, as far as I know, not a good pattern, and causes this, because occultism's rituals inherit from shapeless recipes to use some of the existing code.

I can avoid that on my end, but for a stable solution mcMMO should switch their check to use recipetype, if possible (or check if it is a subclass of shapeless recipe and then skip it)

**Comment by klikli-dev** [comment]
Closed in 058807df2a97855c9d6817769c5be84b39a3db4b but the above message still stands, mcMMO likely needs to adjust their code
