### ISSUE TITLE
[1.21] Cannot load worlds, new or old

### ISSUE THREAD

**Issue by NielsPilgaard** [klikli-dev/occultism#1128]
**Describe the bug**
I cannot join new or existing SP worlds.
I'm not sure it's an Occultism issue tbh, but it might be.

**To Reproduce**
1. Create world

**Expected behavior**
For me to join the newly created world

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.133.0
- Modonomicon Version: modonomicon-1.21-neoforge-1.83.0
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: Same as [yesterday](https://github.com/EnigmaticaModpacks/Enigmatica10/blob/master/changelogs/modlist_1.0.0.md) but with updated mods.

**Additional context**
I first tried joining an existing world, which failed, then I tried creating one and that failed too.

[latest.log](https://gist.github.com/NielsPilgaard/95c6e2e461386be3e3eb238e2f2798fc)
[debug.log](https://gist.github.com/NielsPilgaard/5e9fe1bf2ca86cf09f70243cb6dcc936)

Here's the most relevant log piece I could spot:
```
[18Jun2024 19:40:05.320] [Server thread/ERROR] [net.neoforged.bus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	Index: 6
	Listeners:
		0: @SubscribeEvent: net.neoforged.neoforge.common.NeoForgeEventHandler@789f831d builtinMobSpawnBlocker(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		1: @SubscribeEvent: mekanism.common.CommonWorldTickHandler@3ac4e670 onEntitySpawn(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		2: @SubscribeEvent: net.neoforged.neoforge.common.NeoForgeEventHandler@789f831d onEntityJoinWorld(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		3: @SubscribeEvent: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		4: @SubscribeEvent: class tallestegg.guardvillagers.HandlerEvents onLivingSpawned(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		5: snownee.jade.util.ClientProxy$$Lambda/0x000000080128e140@2ddfd44c
		6: com.klikli_dev.modonomicon.ModonomiconNeo$$Lambda/0x0000000801378460@392bad39
		7: @SubscribeEvent: class com.builtbroken.ai.improvements.modifier.ModifierSystem onEntityJoinWorld(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		8: com.klikli_dev.occultism.Occultism$$Lambda/0x00000008014b9e30@3f3ea00c
		9: @SubscribeEvent: class com.klikli_dev.occultism.handlers.CapabilityEventHandler onEntityJoinWorld(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		10: @SubscribeEvent: class com.direwolf20.justdirethings.common.events.LivingEntityEvents blockJoin(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
		11: @SubscribeEvent: mekanism.client.ClientTickHandler@4945002c onStartTracking(Lnet/neoforged/neoforge/event/entity/EntityJoinLevelEvent;)V
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:637)
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1141)
	at TRANSFORMER/modonomicon@1.83.0/com.klikli_dev.modonomicon.bookstate.BookUnlockStates.update(BookUnlockStates.java:112)
	at TRANSFORMER/modonomicon@1.83.0/com.klikli_dev.modonomicon.bookstate.BookUnlockStateManager.updateAndSyncFor(BookUnlockStateManager.java:62)
	at TRANSFORMER/modonomicon@1.83.0/com.klikli_dev.modonomicon.ModonomiconNeo.lambda$new$4(ModonomiconNeo.java:95)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler$WithPredicate.invoke(ConsumerEventHandler.java:47)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addPlayer(ServerLevel.java:913)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addNewPlayer(ServerLevel.java:905)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:231)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:188)
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8)
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:825)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by NielsPilgaard** [comment]
And all of a sudden, I'm not seeing that in my logs and everything works /shrug
I'll reopen if I manage to reproduce it again :P Sorry for wasting your time!

**Comment by klikli-dev** [comment]
@NielsPilgaard is it possible that modonomicon was updated meanwhile?
The error comes from a library that I recently started using in modonomicon for a minor performance gain and in the first version I introduced some issues. 

That would explain why they are gone now. If there was no modonomicon update it would be good for me to know so I can take another look if I may have missed something

**Comment by NielsPilgaard** [comment]
Yeah could be, I tried a bunch of things :P
