### ISSUE TITLE
Storage Controller crash

### ISSUE THREAD

**Issue by FierceManul** [klikli-dev/occultism#1164]
Storage Controller crash when Too many items.

put items into Storage Controller, let it types > 100%.
connect to logistics.
crash.

- Occultism Version:  1.21-1.136.4

Description: Ticking block entity

java.lang.RuntimeException: Slot 128 not in valid range - [0,128)
	at TRANSFORMER/occultism@1.136.4/com.klikli_dev.occultism.common.misc.MapItemStackHandler.validateSlotIndex(MapItemStackHandler.java:388) ~[occultism-1.21-neoforge-1.136.4.jar%23380!/:1.136.4] {re:classloading}
	at TRANSFORMER/occultism@1.136.4/com.klikli_dev.occultism.common.misc.MapItemStackHandler.extractItem(MapItemStackHandler.java:289) ~[occultism-1.21-neoforge-1.136.4.jar%23380!/:1.136.4] {re:classloading}
	at TRANSFORMER/pipez@1.21-1.2.15/de.maxhenkel.pipez.blocks.tileentity.types.ItemPipeType.insertOrdered(ItemPipeType.java:153) ~[pipez-neoforge-1.21-1.2.15.jar%23382!/:1.21-1.2.15] {re:classloading}
	at TRANSFORMER/pipez@1.21-1.2.15/de.maxhenkel.pipez.blocks.tileentity.types.ItemPipeType.tick(ItemPipeType.java:90) ~[pipez-neoforge-1.21-1.2.15.jar%23382!/:1.21-1.2.15] {re:classloading}
	at TRANSFORMER/pipez@1.21-1.2.15/de.maxhenkel.pipez.blocks.tileentity.PipeLogicTileEntity.tick(PipeLogicTileEntity.java:136) ~[pipez-neoforge-1.21-1.2.15.jar%23382!/:1.21-1.2.15] {re:classloading}
	at TRANSFORMER/pipez@1.21-1.2.15/de.maxhenkel.pipez.corelib.blockentity.SimpleBlockEntityTicker.tick(SimpleBlockEntityTicker.java:14) ~[pipez-neoforge-1.21-1.2.15.jar%23382!/:1.21-1.2.15] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:701) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:778) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:426) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:kubejs.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer from mod nochatreports,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21-20240613.152323-srg.jar%23268!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

**Comment by klikli-dev** [comment]
I think I have a fix (tested with hopper). Please let me know (ping me) if it does not work!
