### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KamiSami** [klikli-dev/occultism#2]
**Describe the bug**
Server crashes upon launch

**To Reproduce**
1. Install this mod to server
2. Launch server

**Expected behavior**
To server work?

**Screenshots**
I have no screenshots but there is crash log

Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Occultism (occultism) has failed to load correctly
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

**System (please complete the following information):**
 I don't think these are necessary?

**Additional context**
Idk

**Comment by klikli-dev** [comment]
That's a bad one, I'll look into it. Got a reference to client code somewhere, forcing it to load. Might take a bit to track that one down.

**Comment by klikli-dev** [comment]
Alpha 0.2.2 will fix this issue. Please test it once it's available on forge and let me know if it worked. Thank you!

**Comment by KamiSami** [comment]
Server starts with this mod in now yeah, haven't got to test the mod yet but i assume it is working as server does load up
