### ISSUE TITLE
class not found: itooltip on server

### ISSUE THREAD

**Issue by kreezxil** [klikli-dev/occultism#426]
**Describe the bug**
crashes dedicated forge server on 1.16.5 for mod version 1.11.4
crash report: https://gist.github.com/543b8390931f99f2b2cf463b26bf937d
snippet from console
```
[12:33:43] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Occultism (occultism) has failed to load correctly
§7java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
```
latest.log: https://gist.github.com/532d34998aa00cc36d8ab948a5258455

**To Reproduce**
1. Put mod on server
2. start server
3. crash

**Expected behavior**
not crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.11.4
- OS:  Linux
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: in current dev version of WOD2 not yet released, i'm the developer. Here's a link to that copy: https://www.dropbox.com/s/9vx8yk0l4jpolgn/World%20of%20Dragons%20II_server_pack.zip?dl=1

**Additional context**
I didn't see a new dependency, will check to see if there is one. otherwise will roll down a version.

**Comment by kreezxil** [comment]
uninstalling and reinstalling didn't fix this. looks you forgot a sideness setting or instruuction somewhere. rolling down to the September 11 2021 version till the next fix.

**Comment by klikli-dev** [comment]
Thanks @kreezxil I indeed missed the distribution sidedness in the new tooltip handler.
