### ISSUE TITLE
1.16.5] Unable to access actuator contents after doing something

### ISSUE THREAD

**Issue by SteamDoge9000** [klikli-dev/occultism#556]
**Describe the bug**
so I have an acutatior that has most of my stuff in it, and i was just putting things into it, but suddenly I crashed and I had no idea, but after trial and error in my world (with me failing to access my actuator) I found that the crash from the nonsense of the crash log was caused by the acutator itself for some uknown reason

**To Reproduce**
unsure; but have saved an instance of the "damaged" world and will continue to play on a backup

**Expected behavior**
Should be obvious, though when clicking on it in this file, it will fail to load up the GUI and 2 times have crashed and produced the same issues, no new mods hve been added and obtifine, while being present, has not caused issues of this sort before

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.22.0.jar
- OS: [e.g. Windows] Windows 10 Operating system
- Minecraft Version: 1.16.5 - 36.2.14
- Modpack Link and Version, or list of mods: 

**Additional context**

the Crash report
https://gist.github.com/SteamDoge9000/15e72530911384005da1f95ed0afe65e

**Comment by klikli-dev** [comment]
Do you have any other crash logs?
This crash is due to an entity being teleported in a tardis

**Comment by SteamDoge9000** [comment]
oh sorry
one moment

il make another report in the proper location for that one, but I think i need to do some more searching, ik its still happening, but maybe the logs might shed some light on this

**Comment by SteamDoge9000** [comment]
. . .da heck? now its not happening in the isolated and untouched instance where this was an issue

I guess it self resolved itself... but I will say that the acutator was storred off dimention, in a tardis to be exact

I guess ill close this issue then, sorry for the waste of time,, though I still find it a bit perplexing that I was having issues. It was late at night and i have no idea if it was a reality or some fever dream I was in, or it was just the game messing with me

ill reopen this issue if it comes up again

**Comment by SteamDoge9000** [comment]
Side Note: I did just update it to the build that was pushed out about 30 or some minuites go

**Comment by SteamDoge9000** [comment]
ok, I managed to find something and its happening again

THIS TIME its not crashing but im pulling it from my logs

this is the error that the log gives whenever I press the keybind (note the keybind is set to the ~ key and it was never an issue before)

[22:14:46] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalStateException: Tag thermal:crafting/locks used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?]
	at net.minecraft.tags.TagRegistry$NamedTag.func_230236_b_(TagRegistry.java:146) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$TagList.func_199799_a(Ingredient.java:272) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.lambda$new$4(Ingredient.java:47) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$$Lambda$2637/2119655249.test(Unknown Source) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_51]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_51]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:47) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:153) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199805_a(Ingredient.java:174) ~[?:?]
	at cofh.core.util.crafting.SecureRecipe.matches(SecureRecipe.java:27) ~[?:1.4.0.3]
	at cofh.core.util.crafting.SecureRecipe.func_77569_a(SecureRecipe.java:17) ~[?:1.4.0.3]
	at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:30) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.md82625d$lambda$getRecipe$1$0(RecipeManager.java:561) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager$$Lambda$37888/1114651438.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.RecipeManager.func_215371_a(RecipeManager.java:562) ~[?:?]
	at com.github.klikli_dev.occultism.common.container.storage.StorageControllerContainerBase.findRecipeForMatrix(StorageControllerContainerBase.java:220) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.common.container.storage.StorageControllerContainerBase.func_75130_a(StorageControllerContainerBase.java:105) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.common.container.storage.StorageRemoteContainer.<init>(StorageRemoteContainer.java:68) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.common.item.storage.StorageRemoteItem.createMenu(StorageRemoteItem.java:148) ~[?:1.16.5-1.22.1]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:226) ~[?:?]
	at com.github.klikli_dev.occultism.network.MessageOpenStorageRemote.onServerReceived(MessageOpenStorageRemote.java:54) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.handleServer(OccultismPacketHandler.java:51) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.lambda$handle$0(OccultismPacketHandler.java:39) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler$$Lambda$40501/1200396962.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.github.klikli_dev.occultism.network.OccultismPacketHandler.handle(OccultismPacketHandler.java:38) ~[?:1.16.5-1.22.1]
	at com.github.klikli_dev.occultism.network.OccultismPackets$$Lambda$29098/1390808782.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$38340/1109497248.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3036/1915624447.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3038/1757437019.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2642/602002603.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$38322/2060564471.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$38782/580123560.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$35597/1440035918.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by SteamDoge9000** [comment]
on closer look, it seems to be some issue wtih the mods acutator and something with CoFH Core

even though its saying stuff about thermal, I have none of the thermal series mods in this custom pack, though the core was needed for some arrow mod that only adds arrows

if you can find a fix or know whats going on, do you think you can fix it and post a hotfix as soon as you can? I cant access my actuator because of this all of my stuff is in it

**Comment by SteamDoge9000** [comment]
it seems that this core mod update was resent and lines up when I started to have issues, this might be something CoFH did recently

if the issue is not being caused by your end then you dont have todo anything, I will however make a comment to this issue, for its also causing it to Travelers Backpacks

**Comment by SteamDoge9000** [comment]
issue was confirmed to be caused by CoFH core's recent update, a fix is under way,

For ANYONE that is having acess issues, use CoFH core 1.3.1 in the meantime; I will close this issue once the update is pushed out with this fix

**Comment by klikli-dev** [comment]
Thanks for the investigation!

**Comment by SteamDoge9000** [comment]
issue seems to have been fixxed
