### ISSUE TITLE
ResourcePack Crash [1.19]

### ISSUE THREAD

**Issue by Speiger** [klikli-dev/occultism#729]
**Describe the bug**
GameCrash due to a unsupported file name in the resourcepack...

**To Reproduce**
Just copy the code you have at the bottom and try to run it with your mod...

**Expected behavior**
That the games doesnt crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.19-1.36.2.jar 
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.19
- Modpack Link and Version, or list of mods: IC2Classic, This mod

**Additional context**
Crashlog:
```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: occultism:textures/About Isabella.txt
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,re:mixin}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.resource.PathResourcePack.lambda$getResources$1(PathResourcePack.java:116) ~[forge-1.19-41.0.62-universal.jar%23160!/:?] {re:classloading}
```

Code that was causing the crash inside your mod:
```java
for(Map.Entry<ResourceLocation, Resource> entry : manager.listResources("textures", T -> T.getPath().endsWith("texture_package.json")).entrySet())
{
}
```

How to fix:
- 1: Remove said file.
- 2: get the filename into a resourcepack friendly format.

**Comment by klikli-dev** [comment]
Very interesting that it's reading that file .. it's an info file from a resourcepack that has become part of occultism. 
While the license requires "About Isabella.txt" to be included I'd say renaming it to about_isabella.txt should not harm
