### ISSUE TITLE
[BUG]: Server crash on Cannot read field "insertGlobalPos" because the return value of "com.github.klikli_dev.occultism.common.entity.job.ManageMachineJob.getManagedMachine()" is null

### ISSUE THREAD

**Issue by Kakoen** [klikli-dev/occultism#906]
### Bug Description

Our server started to crash repeatedly, running All The Mods 8 at version 1.0.14, with occultism 1.73.0. Players report it happens as soon as players load into the chunk with a "Genie Operator".

Caused by: java.lang.NullPointerException: Cannot read field "insertGlobalPos" because the return value of "com.github.klikli_dev.occultism.common.entity.job.ManageMachineJob.getManagedMachine()" is null
	at com.github.klikli_dev.occultism.common.entity.ai.goal.FallbackDepositToControllerGoal.findClosestStorageProxy(FallbackDepositToControllerGoal.java:105) ~[occultism-1.19.2-1.73.0.jar%23658!/:1.19.2-1.73.0]
	at com.github.klikli_dev.occultism.common.entity.ai.goal.FallbackDepositToControllerGoal.m_8037_(FallbackDepositToControllerGoal.java:84) ~[occultism-1.19.2-1.73.0.jar%23658!/:1.19.2-1.73.0]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23775!/:?]

### Logs and Crash Reports

[crash-2023-03-25_04.29.04-server.txt](https://github.com/klikli-dev/occultism/files/11068575/crash-2023-03-25_04.29.04-server.txt)
[2023-03-25-2.log](https://github.com/klikli-dev/occultism/files/11068578/2023-03-25-2.log)

### Bug Reproduction

Not sure how to reproduce the broken state, but the exception is triggered when players connect / enter the base chunk (with a "Genie Operator").

### Expected Behavior

The mod handles the null pointer case without crashing.

### Minecraft Version

1.19.2

### Mod Version

1.73.0

### Modpack

ATM

**Comment by klikli-dev** [comment]
@Kakoen thanks for the report! 
That is a state that should not happen, but it looks like one of the mixins causes it.
I'll look into updating the code to handle that gracefully!

**Comment by klikli-dev** [comment]
@Kakoen that should do it - the release will be on CF within a few minutes/hours (depending on their review process), it should be sufficient to update serverside to fix the crash
